### ISSUE TITLE
readme的里内容有问题

### ISSUE THREAD

**Issue by namejiahui** [opc-source/nacos-sdk-rust-binding-py#4]
在Definition of ClientOptions小节里

    def __init__(self, server_addr, namespace, app_name, username, password):
        self.server_addr = server_addr
        self.server_addr = namespace #这里应该不对
        self.app_name = app_name
        self.username = username
        self.password = password

**Comment by CherishCai** [comment]
喔，确实复制写错了，感谢指出。

**Comment by CherishCai** [comment]
已修正，顺带加上了其它 doc 说明。
Block api: [examples/naming.py](https://github.com/opc-source/nacos-sdk-rust-binding-py/blob/master/examples/naming.py) / [examples/config.py](https://github.com/opc-source/nacos-sdk-rust-binding-py/blob/master/examples/config.py)
Async api: [examples/async_naming.py](https://github.com/opc-source/nacos-sdk-rust-binding-py/blob/master/examples/async_naming.py) / [examples/async_config.py](https://github.com/opc-source/nacos-sdk-rust-binding-py/blob/master/examples/async_config.py)
