### ISSUE TITLE
Feature Request: 能否增加一个 __init__.pyi 文件, 以在使用的过程中可以使得ide识别类型？

### ISSUE THREAD

**Issue by Abeautifulsnow** [opc-source/nacos-sdk-rust-binding-py#5]
我看到安装后的 `nacos_sdk_rust_binding_py` 里面有一个 `__init__.py`，但是只有:

```python
from .nacos_sdk_rust_binding_py import *

__doc__ = nacos_sdk_rust_binding_py.__doc__
if hasattr(nacos_sdk_rust_binding_py, "__all__"):
    __all__ = nacos_sdk_rust_binding_py.__all__
```
这么一点，一些类和方法的使用以及对应api返回的数据类型实在不够透明，我需要去翻看rust代码才能有所了解。

所以基于此，我尝试增加了 `__init__.pyi` 文件，并编辑了 `NacosConfigResponse` 类，

![image](https://github.com/opc-source/nacos-sdk-rust-binding-py/assets/28704977/290244b1-5cbc-4d0c-862d-c2539b136e20)

然后我用的vscode可以查看对应接口的返回了。

![image](https://github.com/opc-source/nacos-sdk-rust-binding-py/assets/28704977/54c8e426-7d18-4265-ad7e-6c6e6a0ec4d6)

**PS:** 虽然这个行为对项目本身没有功能上的增减，但是对于使用者的体验会更友好一些。

我注意到 `pyo3` 当前也在致力于 [类型注释](https://pyo3.rs/v0.21.0-beta.0/python-typing-hints) 的自动化工作，但是还没有终版，目前官方的推荐是在项目根目录手动维护一个 `项目名称.pyi` 文件，然后在通过 `maturin` 发布的时候会随着打包自动在安装包下生成一个一样内容的 `__init__.pyi` 文件。

**Comment by CherishCai** [comment]
欢迎完善，欢迎贡献 👏

**Comment by CherishCai** [comment]
打了个包  0.3.7a0
https://pypi.org/project/nacos-sdk-rust-binding-py/#history

**Comment by Abeautifulsnow** [comment]
> 打了个包 0.3.7a0 https://pypi.org/project/nacos-sdk-rust-binding-py/#history

Nice.
